remote_theme: marella/jekyll-theme-documentation
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

### for local preview 
# gem "github-pages", group: :jekyll_plugins